### ISSUE TITLE
微信公众号文章图片视频等资源无法加载

### ISSUE THREAD

**Issue by nicholasyliu** [li-zyang/zScripts#1]
使用 edge 浏览器打开微信公众号文章时，无法加载图片、视频等资源，排除法确定问题出在这个脚本，顺藤摸瓜找来这边反馈一下。圈外人士，不懂规矩，如有失礼，请见谅。

**Comment by li-zyang** [comment]
OK，我看看

**Comment by li-zyang** [comment]
已修复，更新一下

**Comment by li-zyang** [comment]
是引入的 jQuery 和网页原来的 jQuery 有版本冲突，GreasyMonkey / TemperMonkey 等等脚本管理器把脚本本身放到沙箱里面运行，但是 `@require` 的 lib 就直接释放到网页里面去了，有(hen)些(duo)网站还在用 jQuery v1，然后兼容性就很差
网上查了一下，玄学解决方法是添加两个脚本管理器的 API，添加完不一定要用，但是就可以把 require 的库放到沙箱里面 =_=
