### ISSUE TITLE
其它网页适配的问题

### ISSUE THREAD

**Issue by FduJyy** [li-zyang/zScripts#2]
作者您好。由于我使用的显示器比例是 21:9，所以类似 wikipedia 或者 nga 之类的网页铺满整个宽度，看着会很累，希望能够用脚本限制这类网页内容显示的宽度。

我在脚本的 forced_url_pat 中加入这两个网页的域名，并未起到效果。不知道需要如何实现限制网页内容显示的宽度这个功能？即使内容不随浏览器宽度变化。

**Comment by li-zyang** [comment]
理论上如果是匹配的网页会把原来 `<body>` 宽度限制在 832px 以下（不过这种方法对于一些网站仍然是无效的，旧式页面一般有用），forced_url_pat 里面的项是正则表达式来的，不知道你添加的项是否写对了？
类似于这样：
```
  let forced_url_pat = [
    /https?:\/\/man.openbsd.org\/.*/,
    /https?:\/\/man7.org\/.*/
  ];
```

**Comment by FduJyy** [comment]
@li-zyang 
我是这样写的：
```javascript
let forced_url_pat = [
    /https?:\/\/man.openbsd.org\/.*/,
    /https?:\/\/man7.org\/.*/,
    /https?:\/\/bbs.nga.cn\/.*/,
    /https?:\/\/en.wikipedia.org\/.*/
  ];
```
结果是如图 wikipedia 排版劣化，bbs.nga.cn 一直在加载，无法成功载入网页。如果想要简单地降低宽度应该要如何修改呢？谢谢
![image.png](https://i.loli.net/2020/07/18/1hsRmjy3dJg9xDf.png)

**Comment by li-zyang** [comment]
看了下，Wikipedia 和 NGA 都是相对复杂的网页，不是这个脚本的目标，如果强行应用确实会导致排版错误的，如果想要针对特定的网站可以安装一个 Stylus 插件，在 [userstyle](https://userstyles.org/) 上搜索网站相关的样式表安装（比如 Wikipedia 有 Wikipedia Clean White 和 Wikipedia Clean Dark，对版式有很大的改善）
