### ISSUE TITLE
Other issues

### ISSUE THREAD

**Issue by DonaldTsang** [li-zyang/zScripts#3]
What would be the difference between nofollow and noreferrer?
- https://greasyfork.org/en/scripts/404798-nofollow
- https://greasyfork.org/en/scripts/25124-add-rel-noreferrer-noopener-to-voat

For reference these are for https://github.com/li-zyang/zScripts/tree/master/noopener-everywhere

**Comment by li-zyang** [comment]
### nofollow is for SEO
> Indicates that the linked document is not endorsed by the author of this one, for example if it has no control over it, if it is a bad example or if there is commercial relationship between the two (sold link). This link type may be used by some search engines that use popularity ranking techniques.

### noreferrer is for privacy
> Prevents the browser, when navigating to another page, to send this page address, or any other value, as referrer via the Referer: HTTP header.

(ie. this header is not sent)
![Snipaste_2020-08-18_00-18-43](https://user-images.githubusercontent.com/57308476/90419192-cdeb3600-e0e8-11ea-8a66-b8c52274dde2.png)
